export default {
    common:{cancel:'キャンセル',save:'保存',edit:'編集',remove:'削除',details:'詳細',search:'検索',all:'すべて',next:'次へ',confirm:'確認',cards:'{count} 枚'},
    accountNav:{home:'マイページ',orders:'ボックス注文',shipping:'配送注文',payments:'支払い方法',addresses:'住所録',settings:'個人設定'},
    draw:{confirm:'購入確認',times:'抽選回数',timesValue:'{count} 回',cost:'今回の消費',balance:'現在の残高',after:'購入後の残高',notice:'確率は残り在庫に応じて変動します。10回引きの割引、累積保証、追加確定枠はありません。購入確認後、パック選択と開封アニメーションに進みます。',recharge:'チャージする',buy:'購入を確定',insufficient:'残高が不足しています。先にチャージしてください'},
    arrivals:{title:'新着商品',all:'すべての新着を見る',weekly:'今週の新着',previous:'前の新着グループ',next:'次の新着グループ',list:'新着ボックス横スクロール一覧',tags:'商品タグ'},
    accountHome:{title:'マイページ',subtitle:'OK Coin とカードコレクションを管理します。',export:'資産履歴をエクスポート',balance:'OK Coin 残高',balanceHint:'チャージ、付与、買取の Coin はすべて共通残高に反映されます',recharge:'Coinをチャージ',transactions:'取引明細',stored:'保管中のカード',shippingThreshold:'選択カード合計 2,000 Coin 以上で配送可能',shipPhysical:'現物配送を申請',warehouse:'カード倉庫',normalHint:'獲得したカードを確認・管理します',recycleHint:'買取するカードを選択してください',shippingHint:'配送するカードを選択してください',batchRecycle:'まとめて買取',shipping:'配送を申請',storedStatus:'保管中',shippingLocked:'配送ロック',search:'カード名を検索…',recyclable:'買取価格 {coin} Coin',openBox:'新しいボックスを開く',selected:'{count} 枚選択中',estimate:'獲得予定 {coin} Coin',cardTotal:'カード合計 {coin} Coin',confirmRecycle:'買取を確定',recycleWarning:'買取後は取り消せません。もう一度ご確認ください',shippingStarted:'配送申請に進みました'},
    cards:{pikachu:{name:'ピカチュウ VMAX',tag:'PSA 10'},gengar:{name:'ゲンガー VMAX',tag:'PSA 9'},mewtwo:{name:'ミュウツー GX',tag:'未鑑定'},eevee:{name:'イーブイ限定版',tag:'限定版'}},
    orders:{title:'ボックス注文',subtitle:'ボックス購入履歴のみ表示します。チャージと買取は取引明細をご覧ください。',newBox:'新しいボックスを開く',balance:'OK Coin 残高',recharge:'Coinをチャージ',transactions:'取引明細',allStatus:'すべての状態',completed:'完了',processing:'処理中',allTypes:'すべての抽選タイプ',single:'1回引く',ten:'10回引く',searchPlaceholder:'注文番号を検索',headers:['注文番号','ボックスとロット','抽選タイプ','消費 Coin','注文日時','状態','操作'],batch:'ロット OK-2608',view:'結果を見る'},
    shipping:{title:'配送注文',subtitle:'カード現物配送の進捗と最新状況を追跡します。',statuses:['すべて','審査待ち','発送待ち','配送中','受取済み'],my:'配送注文',count:'{count} 件の注文',search:'発送番号を検索…',headers:['発送番号 / 申請日時','状態','配送先','カード / Coin','配送業者','最新状況','操作'],pendingCarrier:'未割当',packing:'倉庫で梱包中',inTransit:'配送中',pendingShip:'発送待ち',delivered:'受取済み',eta:'8月10日到着予定',deliveredAt:'7月18日に配達済み'},
    addresses:{title:'住所録',subtitle:'カード配送に使用する住所を管理します。',add:'＋ 新しい住所',default:'既定の住所',snapshot:'送信済みの配送注文には申請時の住所が保存されます。',setDefault:'既定に設定',saved:'住所を保存しました',defaultSaved:'既定の住所に設定しました',regionsTitle:'配送対応地域',regions:'日本 · 中国本土 · マカオ',threshold:'選択カード合計が 2,000 Coin 以上で通常配送料無料です。',new:'配送先を追加',country:'国または地域',china:'中国本土',japan:'日本',macau:'マカオ',recipient:'受取人名',phone:'国番号と電話番号',address:'住所',street:'町名、番地',city:'市区町村',province:'都道府県',postal:'郵便番号',save:'住所を保存'},
    settings:{title:'個人設定',subtitle:'プロフィール、アカウントの安全性、設定を管理します。',personal:'♙ 個人情報',nickname:'ニックネーム',birth:'生年月日',security:'♧ アカウントセキュリティ',email:'登録メール',phone:'登録電話番号',password:'ログインパスワード',passwordHint:'定期的な変更で安全性を高められます',change:'変更',changePassword:'パスワード変更',preferences:'☷ 環境設定',language:'表示言語',languageHint:'アカウントとブラウザに保存',notifications:'通知',notificationsHint:'残高、配送、サポート通知を受け取る',autoLogin:'自動ログイン',autoLoginHint:'信頼できる端末でのみログインを維持',motion:'動きを減らす',motionHint:'開封アニメーションと画面効果を軽減',management:'アカウント管理',devices:'ログイン端末',deviceHint:'現在の端末：Windows · Shanghai',manageDevices:'端末を管理',logout:'ログアウト',logoutHint:'次回利用時に再ログインが必要です',logoutButton:'ログアウト',close:'アカウント削除を申請',closeHint:'資産処理後、30日間の待機期間があります',closeButton:'削除手続きを開始'},
    detail:{breadcrumb:'ブラインドボックス',licensed:'公式ライセンス',hot:'人気',pikachu:'ピカチュウ',description:'ロット OK-PIKA-2608 · ピカチュウ、イーブイ、ミュウツーなどの公式ライセンスカードを収録。数量限定、非復元抽選です。',single:'1回引く',ten:'10回引く',balance:'現在の残高',stock:'残り在庫',updated:'確率更新：たった今',ruleAlert:'確率は残り在庫に応じて変動します。累積保証や10回引きの確定枠はありません。',pool:'リアルタイム賞品プール',poolHint:'現在の確率合計 100% · 抽選ごとにカードを1枚獲得',tiers:['1等','2等','3等'],tierChance:'等級合計確率 {chance}',sold:'抽選済み',recyclable:'買取 {coin} Coin',initial:'初期在庫',live:'現在の確率',guarantee:'最低保証賞品',randomCard:'同等価値のポケモンカードをランダムで1枚獲得',randomHint:'配送申請時に同等価値の実物カードをランダムで選択します。下位への交換はありません。',slots:'残り枠',rules:[['ルール','各ロットは固定数量の限定プールで、非復元抽選です。購入後に自動開封します。'],['カード買取','保管中カードは固定 Coin で買取できます。確定後は取り消せません。'],['現物配送','選択カード合計 2,000 Coin 以上で通常配送料無料です。'],['返金と異常','決済結果が不明な場合は最終状態を確認してください。重複送信は行いません。']],drawNow:'今すぐ1回引く'},
    simple:{paymentTitle:'支払い方法',paymentHint:'保存済みカードを安全に管理します。Alipay はチャージ時に選択でき、事前登録は不要です。',expiry:'有効期限 {date}',defaultCard:'既定のカード',addCard:'カードを追加',transactions:'取引明細',transactionsHint:'チャージ、購入、買取、付与、補償、訂正をまとめて表示します。',transactionHeaders:['日時','種類','概要','Coin 変動','残高'],faqTitle:'よくある質問',faqHint:'アカウント、チャージ、確率、買取、配送について検索できます。',faqSearch:'キーワードで検索…',faqCategories:['アカウントとログイン','OK Coin とチャージ','ボックスと確率','カード買取','保管と配送','返金と安全性'],faqQuestions:['OK Coin とは何ですか？','カードプールの確率はどう計算されますか？','なぜ10回引きに追加保証がないのですか？','カードを OK Coin に交換する方法は？','現物配送の条件は？','購入後に返金または再抽選できますか？'],faqAnswer:'リアルタイム在庫と動的確率を表示します。各ロットは非復元抽選で、累積保証や10回引きの確定枠はありません。さらにサポートが必要な場合はお問い合わせください。',contactTitle:'お問い合わせ',contactHint:'問題をご記入ください。サポートチームが2営業日以内に返信します。',prepare:'ご用意いただく情報',prepareHint:'注文に関する場合は、マスキングした注文番号とスクリーンショットをご提供ください。パスワード、認証コード、完全なカード情報は送信しないでください。',category:'カテゴリー',categories:['ボックス注文','チャージと支払い','カードと配送'],name:'氏名',email:'メール',orderOptional:'注文番号（任意）',description:'お問い合わせ内容',attachment:'添付（最大3件）',submit:'送信',submitted:'送信しました',ticket:'受付番号：OK-260808-1042',emailSent:'確認メールを送信しました。',authTitles:{register:'アカウント作成',forgot:'パスワードを忘れた場合',reset:'パスワード再設定',activation:'アカウント有効化',login:'OK Kard Empire にログイン'},registerHint:'メールと電話番号の登録、18歳以上の確認が必要です。',loginHint:'Coin、注文、カード資産へ安全にアクセスします。',passwordLogin:'パスワード',codeLogin:'認証コード',account:'メールまたは電話番号',password:'パスワード',birth:'生年月日',consent:'18歳以上で、利用規約とプライバシーポリシーに同意します',continue:'続ける',forgotLink:'パスワードをお忘れですか？',registerLink:'アカウントをお持ちでない方はこちら',submittedDemo:'デモ手続きを送信しました'},
    opening:{headings:{choose:'次の驚きがここにあります',shuffled:'直感が答えへ導きます',shuffle:'幸運をシャッフル',focus:'このパックです',tear:'自分の手で開ける瞬間',opening:'封を切りました',video:'まもなく結果発表',handoff:'パックを開封しました'},instructions:{choose:'左右にドラッグしてパックを選ぶか、先にシャッフルできます',shuffle:'シャッフル中です…',focus:'選んだパックを手前に移動しています',tear:'白線の左端を押さえ、右へスライドしてください',opening:'選んだパックを開けています…',video:'開封アニメーションを再生中',handoff:'開封体験が完了しました'},experience:'開封体験',draws:'{count} 回抽選',close:'開封アニメーションを閉じる',preparing:'パックを準備中…',threeError:'3Dパックを読み込めません。ブラウザのハードウェアアクセラレーションをご確認ください。',reload:'再読み込み',back:'戻る',tearAria:'左から右へ封を切るか、右矢印キーを連続して押す',left:'パックを左へ回転',right:'パックを右へ回転',shuffling:'シャッフル中…',shuffleAgain:'もう一度シャッフル',shuffle:'シャッフル',choose:'このパックを選ぶ ↗',gesture:'マウスまたは指で左から右へ · キーボードは → を連続入力',wheel:'左右にドラッグできる3Dパックホイール',play:'開封動画を再生',videoError:'動画を再生できません。しばらくしてからお試しください。',result:'結果を見る',skip:'アニメーションをスキップ',resultTitle:'抽選結果',prevCard:'前のカード',nextCard:'次のカード',recycle:'買取価格',viewCard:'{number}枚目を見る',demo:'デモ結果 · 実際の賞品ではありません',wonCards:'コレクションカードを {count} 枚獲得しました',stored:'カードをコレクション倉庫に保存しました',againDemo:'もう一度体験',again:'続けて引く',finish:'完了'}
  } as const
