export default {
    common:{cancel:'取消',save:'保存',edit:'编辑',remove:'删除',details:'详情',search:'搜索',all:'全部',next:'下一步',confirm:'确认',cards:'{count} 张'},
    accountNav:{home:'个人主页',orders:'盲盒订单',shipping:'物流订单',payments:'支付方式',addresses:'地址簿',settings:'个人设置'},
    draw:{confirm:'购买确认',times:'抽取次数',timesValue:'{count} 次',cost:'本次消耗',balance:'当前余额',after:'购买后余额',notice:'概率会随剩余库存动态变化。十连抽不打折，也不存在累计保底或额外必出机制。确认购买后进入选包与开包动画。',recharge:'去充值',buy:'确认购买',insufficient:'余额不足，请先充值'},
    arrivals:{title:'新品上线',all:'查看全部新品',weekly:'本周上新',previous:'查看上一组新品',next:'查看下一组新品',list:'新品盲盒横向列表',tags:'商品标签'},
    accountHome:{title:'个人主页',subtitle:'管理你的 OK Coin 与卡牌收藏。',export:'导出资产记录',balance:'OK Coin 余额',balanceHint:'所有充值、赠送与回收 Coin 均进入统一余额',recharge:'充值 Coin',transactions:'收支明细',stored:'保管中的卡牌',shippingThreshold:'发货门槛为所选卡牌合计 2,000 Coin',shipPhysical:'申请实物发货',warehouse:'卡牌仓库',normalHint:'查看并管理已获得的卡牌',recycleHint:'请选择要回收的卡牌',shippingHint:'请选择要申请发货的卡牌',batchRecycle:'批量回收',shipping:'申请发货',storedStatus:'保管中',shippingLocked:'发货锁定',search:'搜索卡牌名称…',recyclable:'可回收 {coin} Coin',openBox:'开启新盲盒',selected:'已选择 {count} 张',estimate:'预计获得 {coin} Coin',cardTotal:'卡牌合计 {coin} Coin',confirmRecycle:'确认回收',recycleWarning:'请再次确认回收，完成后不可撤销',shippingStarted:'已进入发货申请流程'},
    cards:{pikachu:{name:'皮卡丘 VMAX',tag:'PSA 10'},gengar:{name:'耿鬼 VMAX',tag:'PSA 9'},mewtwo:{name:'超梦 GX',tag:'未评级'},eevee:{name:'伊布限定版',tag:'限量版'}},
    orders:{title:'盲盒订单',subtitle:'仅展示盲盒购买记录，充值与回收记录请前往收支明细。',newBox:'开启新盲盒',balance:'OK Coin 余额',recharge:'充值 Coin',transactions:'收支明细',allStatus:'全部状态',completed:'已完成',processing:'处理中',allTypes:'全部抽取类型',single:'单抽',ten:'十连抽',searchPlaceholder:'搜索订单号',headers:['订单号','盲盒与批次','抽取类型','消耗 Coin','下单时间','状态','操作'],batch:'批次 OK-2608',view:'查看结果'},
    shipping:{title:'物流订单',subtitle:'跟踪卡牌实物发货进度与最新物流节点。',statuses:['全部','待审核','待发货','运输中','已签收'],my:'我的物流订单',count:'共 {count} 个订单',search:'输入发货单号搜索…',headers:['发货单号 / 申请时间','状态','收货信息','卡牌 / Coin','承运信息','最新节点','操作'],pendingCarrier:'待分配',packing:'正在仓库打包',inTransit:'运输中',pendingShip:'待发货',delivered:'已签收',eta:'预计 8 月 10 日送达',deliveredAt:'7 月 18 日已签收'},
    addresses:{title:'地址簿',subtitle:'管理卡牌发货使用的收货信息。',add:'＋ 添加新地址',default:'默认地址',snapshot:'已提交的发货订单会保留提交时的地址快照。',setDefault:'设为默认',saved:'地址已保存',defaultSaved:'已设为默认地址',regionsTitle:'支持配送地区',regions:'日本 · 中国大陆 · 澳门',threshold:'所选卡牌合计达到 2,000 Coin 后可申请标准包邮。',new:'新增收货地址',country:'国家或地区',china:'中国大陆',japan:'日本',macau:'澳门',recipient:'收件人姓名',phone:'国际区号与电话',address:'地址',street:'街道、门牌号',city:'城市',province:'州 / 省',postal:'邮编',save:'保存地址'},
    settings:{title:'个人中心设置',subtitle:'管理个人资料、账户安全与偏好设置。',personal:'♙ 个人信息',nickname:'昵称',birth:'出生日期',security:'♧ 账户安全',email:'绑定邮箱',phone:'绑定手机号',password:'登录密码',passwordHint:'定期修改密码可提高账户安全性',change:'更换',changePassword:'修改密码',preferences:'☷ 偏好设置',language:'界面语言',languageHint:'同步保存到账户和浏览器',notifications:'消息通知',notificationsHint:'接收余额、物流和客服通知',autoLogin:'自动登录',autoLoginHint:'仅在受信任设备上保持登录',motion:'减少动态效果',motionHint:'降低开盒动画和页面动态效果',management:'账号管理',devices:'登录设备',deviceHint:'当前设备：Windows · Shanghai',manageDevices:'管理设备',logout:'退出当前账号',logoutHint:'下次使用时需要重新登录',logoutButton:'退出登录',close:'申请注销账号',closeHint:'需完成资产处理并进入 30 天等待期',closeButton:'开始注销'},
    detail:{breadcrumb:'盲盒专区',licensed:'官方授权',hot:'热门',pikachu:'皮卡丘',description:'批次 OK-PIKA-2608 · 汇集皮卡丘、伊布、超梦等宝可梦授权收藏卡牌。有限卡池，不放回抽取。',single:'单次抽取',ten:'十连抽',balance:'当前余额',stock:'剩余库存',updated:'概率更新时间：刚刚',ruleAlert:'概率随剩余库存动态变化；不存在累计保底或十连必出机制。',pool:'实时卡池详情',poolHint:'当前概率合计 100% · 每次抽取必得一张卡牌',tiers:['一等奖','二等奖','三等奖'],tierChance:'奖级总概率 {chance}',sold:'已抽完',recyclable:'可回收 {coin} Coin',initial:'初始库存',live:'实时概率',guarantee:'保底奖励 · 最低奖品',randomCard:'随机获得同价值档位宝可梦卡牌一张',randomHint:'申请发货时由平台随机选择同价值档位实际卡牌，不会降级替换。',slots:'剩余名额',rules:[['玩法规则','每个批次为固定数量的有限卡池，采用不放回抽取。购买成功后自动开盒。'],['卡牌回收','保管中的卡牌可按锁定 Coin 回收，确认后不可撤销。'],['实物发货','所选卡牌合计达到 2,000 Coin 后可申请标准包邮。'],['退款与异常','遇到扣款无结果等异常时先查询最终状态，系统不会重复提交。']],drawNow:'立即单抽'},
    simple:{paymentTitle:'支付方式',paymentHint:'安全管理已保存的信用卡。支付宝在充值时选择，无需预先绑定。',expiry:'有效期 {date}',defaultCard:'默认卡',addCard:'添加信用卡',transactions:'交易明细',transactionsHint:'统一展示充值、购买、回收、赠送、补偿与冲正记录。',transactionHeaders:['时间','类型','摘要','Coin 变化','余额'],faqTitle:'常见问题',faqHint:'搜索账户、充值、概率、回收与发货相关问题。',faqSearch:'搜索问题关键词…',faqCategories:['账户与登录','OK Coin 与充值','盲盒与概率','卡牌回收','仓储与发货','退款与安全'],faqQuestions:['OK Coin 是什么？','卡池概率如何计算？','为什么十连抽没有额外保底？','卡牌如何回收为 OK Coin？','实物发货需要满足什么条件？','购买后可以退款或重抽吗？'],faqAnswer:'页面展示实时库存与动态概率。每个批次采用不放回抽取，不存在累计保底或十连必出机制。需要进一步帮助时，可提交客服工单。',contactTitle:'联系我们',contactHint:'描述你遇到的问题，我们的支持团队将在 2 个工作日内回复。',prepare:'需要准备的信息',prepareHint:'如与订单有关，请提供脱敏后的订单号和问题截图。请勿提交密码、验证码或完整支付卡信息。',category:'问题分类',categories:['盲盒订单','充值与支付','卡牌与发货'],name:'姓名',email:'邮箱',orderOptional:'订单号（可选）',description:'问题描述',attachment:'附件（最多 3 个）',submit:'提交工单',submitted:'工单已提交',ticket:'工单编号：OK-260808-1042',emailSent:'确认邮件已发送到你的邮箱。',authTitles:{register:'创建账户',forgot:'找回密码',reset:'重置密码',activation:'完成账户激活',login:'登录 OK Kard Empire'},registerHint:'需完成邮箱、手机号双绑定与 18+ 确认。',loginHint:'安全访问你的 Coin、订单与卡牌资产。',passwordLogin:'密码登录',codeLogin:'验证码登录',account:'邮箱或手机号',password:'密码',birth:'出生日期',consent:'我确认已年满 18 周岁，并同意服务条款与隐私政策',continue:'继续',forgotLink:'忘记密码？',registerLink:'还没有账户？立即注册',submittedDemo:'演示流程已提交'},
    opening:{headings:{choose:'你的下一份惊喜，藏在这里',shuffled:'直觉，会带你找到它',shuffle:'让好运重新排列',focus:'就是这一包',tear:'亲手，开启这一刻',opening:'封口已划开',video:'惊喜，即将揭晓',handoff:'卡包已开启'},instructions:{choose:'左右拖动轮盘，直接点选卡包，也可以先洗牌',shuffle:'正在洗牌，请稍候…',focus:'正在将你选择的卡包移到面前',tear:'按住白线左端，向右划开卡包',opening:'正在打开你选择的卡包…',video:'正在播放开包动画',handoff:'前段开包体验已完成'},experience:'开包体验',draws:'{count} 次抽取',close:'关闭开包动画',preparing:'正在准备卡包…',threeError:'暂时无法加载 3D 卡包，请确认浏览器已开启硬件加速。',reload:'重新加载',back:'返回',tearAria:'从左向右划开封口，或连续按右方向键',left:'向左旋转卡包',right:'向右旋转卡包',shuffling:'洗牌中…',shuffleAgain:'再次洗牌',shuffle:'洗牌',choose:'选择当前卡包 ↗',gesture:'鼠标或手指从左向右划开 · 键盘可连续按 →',wheel:'可左右拖动的立体卡包轮盘',play:'播放开包视频',videoError:'视频暂时无法播放，请稍后重试。',result:'查看结果',skip:'跳过动画',resultTitle:'抽取结果',prevCard:'上一张卡牌',nextCard:'下一张卡牌',recycle:'回收价值',viewCard:'查看第 {number} 张卡牌',demo:'演示结果 · 不代表实际奖品',wonCards:'本次共获得 {count} 张收藏卡牌',stored:'卡牌已收入你的收藏仓库',againDemo:'再体验一次',again:'继续抽取',finish:'完成'}
  } as const
