export default {
    common:{cancel:'取消',save:'儲存',edit:'編輯',remove:'刪除',details:'詳情',search:'搜尋',all:'全部',next:'下一步',confirm:'確認',cards:'{count} 張'},
    accountNav:{home:'個人主頁',orders:'盲盒訂單',shipping:'物流訂單',payments:'付款方式',addresses:'地址簿',settings:'個人設定'},
    draw:{confirm:'購買確認',times:'抽取次數',timesValue:'{count} 次',cost:'本次消耗',balance:'目前餘額',after:'購買後餘額',notice:'機率會隨剩餘庫存動態變化。十連抽不打折，也不存在累計保底或額外必出機制。確認購買後進入選包與開包動畫。',recharge:'前往儲值',buy:'確認購買',insufficient:'餘額不足，請先儲值'},
    arrivals:{title:'新品上線',all:'查看全部新品',weekly:'本週上新',previous:'查看上一組新品',next:'查看下一組新品',list:'新品盲盒橫向列表',tags:'商品標籤'},
    accountHome:{title:'個人主頁',subtitle:'管理你的 OK Coin 與卡牌收藏。',export:'匯出資產記錄',balance:'OK Coin 餘額',balanceHint:'所有儲值、贈送與回收 Coin 均進入統一餘額',recharge:'儲值 Coin',transactions:'收支明細',stored:'保管中的卡牌',shippingThreshold:'發貨門檻為所選卡牌合計 2,000 Coin',shipPhysical:'申請實物發貨',warehouse:'卡牌倉庫',normalHint:'查看並管理已獲得的卡牌',recycleHint:'請選擇要回收的卡牌',shippingHint:'請選擇要申請發貨的卡牌',batchRecycle:'批量回收',shipping:'申請發貨',storedStatus:'保管中',shippingLocked:'發貨鎖定',search:'搜尋卡牌名稱…',recyclable:'可回收 {coin} Coin',openBox:'開啟新盲盒',selected:'已選擇 {count} 張',estimate:'預計獲得 {coin} Coin',cardTotal:'卡牌合計 {coin} Coin',confirmRecycle:'確認回收',recycleWarning:'請再次確認回收，完成後不可撤銷',shippingStarted:'已進入發貨申請流程'},
    cards:{pikachu:{name:'皮卡丘 VMAX',tag:'PSA 10'},gengar:{name:'耿鬼 VMAX',tag:'PSA 9'},mewtwo:{name:'超夢 GX',tag:'未評級'},eevee:{name:'伊布限定版',tag:'限量版'}},
    orders:{title:'盲盒訂單',subtitle:'僅展示盲盒購買記錄，儲值與回收記錄請前往收支明細。',newBox:'開啟新盲盒',balance:'OK Coin 餘額',recharge:'儲值 Coin',transactions:'收支明細',allStatus:'全部狀態',completed:'已完成',processing:'處理中',allTypes:'全部抽取類型',single:'單抽',ten:'十連抽',searchPlaceholder:'搜尋訂單號',headers:['訂單號','盲盒與批次','抽取類型','消耗 Coin','下單時間','狀態','操作'],batch:'批次 OK-2608',view:'查看結果'},
    shipping:{title:'物流訂單',subtitle:'追蹤卡牌實物發貨進度與最新物流節點。',statuses:['全部','待審核','待發貨','運輸中','已簽收'],my:'我的物流訂單',count:'共 {count} 個訂單',search:'輸入發貨單號搜尋…',headers:['發貨單號 / 申請時間','狀態','收貨資訊','卡牌 / Coin','承運資訊','最新節點','操作'],pendingCarrier:'待分配',packing:'正在倉庫打包',inTransit:'運輸中',pendingShip:'待發貨',delivered:'已簽收',eta:'預計 8 月 10 日送達',deliveredAt:'7 月 18 日已簽收'},
    addresses:{title:'地址簿',subtitle:'管理卡牌發貨使用的收貨資訊。',add:'＋ 新增地址',default:'預設地址',snapshot:'已提交的發貨訂單會保留提交時的地址快照。',setDefault:'設為預設',saved:'地址已儲存',defaultSaved:'已設為預設地址',regionsTitle:'支援配送地區',regions:'日本 · 中國大陸 · 澳門',threshold:'所選卡牌合計達到 2,000 Coin 後可申請標準免運。',new:'新增收貨地址',country:'國家或地區',china:'中國大陸',japan:'日本',macau:'澳門',recipient:'收件人姓名',phone:'國際區號與電話',address:'地址',street:'街道、門牌號',city:'城市',province:'州 / 省',postal:'郵遞區號',save:'儲存地址'},
    settings:{title:'個人中心設定',subtitle:'管理個人資料、帳戶安全與偏好設定。',personal:'♙ 個人資訊',nickname:'暱稱',birth:'出生日期',security:'♧ 帳戶安全',email:'綁定信箱',phone:'綁定手機號',password:'登入密碼',passwordHint:'定期修改密碼可提高帳戶安全性',change:'更換',changePassword:'修改密碼',preferences:'☷ 偏好設定',language:'介面語言',languageHint:'同步儲存至帳戶和瀏覽器',notifications:'訊息通知',notificationsHint:'接收餘額、物流和客服通知',autoLogin:'自動登入',autoLoginHint:'僅在受信任裝置上保持登入',motion:'減少動態效果',motionHint:'降低開盒動畫和頁面動態效果',management:'帳號管理',devices:'登入裝置',deviceHint:'目前裝置：Windows · Shanghai',manageDevices:'管理裝置',logout:'登出目前帳號',logoutHint:'下次使用時需要重新登入',logoutButton:'登出',close:'申請註銷帳號',closeHint:'需完成資產處理並進入 30 天等待期',closeButton:'開始註銷'},
    detail:{breadcrumb:'盲盒專區',licensed:'官方授權',hot:'熱門',pikachu:'皮卡丘',description:'批次 OK-PIKA-2608 · 匯集皮卡丘、伊布、超夢等寶可夢授權收藏卡牌。有限卡池，不放回抽取。',single:'單次抽取',ten:'十連抽',balance:'目前餘額',stock:'剩餘庫存',updated:'機率更新時間：剛剛',ruleAlert:'機率隨剩餘庫存動態變化；不存在累計保底或十連必出機制。',pool:'即時卡池詳情',poolHint:'目前機率合計 100% · 每次抽取必得一張卡牌',tiers:['一等獎','二等獎','三等獎'],tierChance:'獎級總機率 {chance}',sold:'已抽完',recyclable:'可回收 {coin} Coin',initial:'初始庫存',live:'即時機率',guarantee:'保底獎勵 · 最低獎品',randomCard:'隨機獲得同價值檔位寶可夢卡牌一張',randomHint:'申請發貨時由平台隨機選擇同價值檔位實際卡牌，不會降級替換。',slots:'剩餘名額',rules:[['玩法規則','每個批次為固定數量的有限卡池，採用不放回抽取。購買成功後自動開盒。'],['卡牌回收','保管中的卡牌可按鎖定 Coin 回收，確認後不可撤銷。'],['實物發貨','所選卡牌合計達到 2,000 Coin 後可申請標準免運。'],['退款與異常','遇到扣款無結果等異常時先查詢最終狀態，系統不會重複提交。']],drawNow:'立即單抽'},
    simple:{paymentTitle:'付款方式',paymentHint:'安全管理已儲存的信用卡。支付寶在儲值時選擇，無需預先綁定。',expiry:'有效期 {date}',defaultCard:'預設卡',addCard:'新增信用卡',transactions:'交易明細',transactionsHint:'統一展示儲值、購買、回收、贈送、補償與沖正記錄。',transactionHeaders:['時間','類型','摘要','Coin 變化','餘額'],faqTitle:'常見問題',faqHint:'搜尋帳戶、儲值、機率、回收與發貨相關問題。',faqSearch:'搜尋問題關鍵字…',faqCategories:['帳戶與登入','OK Coin 與儲值','盲盒與機率','卡牌回收','倉儲與發貨','退款與安全'],faqQuestions:['OK Coin 是什麼？','卡池機率如何計算？','為什麼十連抽沒有額外保底？','卡牌如何回收為 OK Coin？','實物發貨需要滿足什麼條件？','購買後可以退款或重抽嗎？'],faqAnswer:'頁面展示即時庫存與動態機率。每個批次採用不放回抽取，不存在累計保底或十連必出機制。需要進一步協助時，可提交客服工單。',contactTitle:'聯絡我們',contactHint:'描述你遇到的問題，我們的支援團隊將在 2 個工作日內回覆。',prepare:'需要準備的資訊',prepareHint:'如與訂單有關，請提供脫敏後的訂單號和問題截圖。請勿提交密碼、驗證碼或完整支付卡資訊。',category:'問題分類',categories:['盲盒訂單','儲值與付款','卡牌與發貨'],name:'姓名',email:'信箱',orderOptional:'訂單號（選填）',description:'問題描述',attachment:'附件（最多 3 個）',submit:'提交工單',submitted:'工單已提交',ticket:'工單編號：OK-260808-1042',emailSent:'確認郵件已發送到你的信箱。',authTitles:{register:'建立帳戶',forgot:'找回密碼',reset:'重設密碼',activation:'完成帳戶啟用',login:'登入 OK Kard Empire'},registerHint:'需完成信箱、手機號雙綁定與 18+ 確認。',loginHint:'安全存取你的 Coin、訂單與卡牌資產。',passwordLogin:'密碼登入',codeLogin:'驗證碼登入',account:'信箱或手機號',password:'密碼',birth:'出生日期',consent:'我確認已年滿 18 歲，並同意服務條款與隱私政策',continue:'繼續',forgotLink:'忘記密碼？',registerLink:'還沒有帳戶？立即註冊',submittedDemo:'示範流程已提交'},
    opening:{headings:{choose:'你的下一份驚喜，藏在這裡',shuffled:'直覺，會帶你找到它',shuffle:'讓好運重新排列',focus:'就是這一包',tear:'親手，開啟這一刻',opening:'封口已劃開',video:'驚喜，即將揭曉',handoff:'卡包已開啟'},instructions:{choose:'左右拖動輪盤，直接點選卡包，也可以先洗牌',shuffle:'正在洗牌，請稍候…',focus:'正在將你選擇的卡包移到面前',tear:'按住白線左端，向右劃開卡包',opening:'正在打開你選擇的卡包…',video:'正在播放開包動畫',handoff:'前段開包體驗已完成'},experience:'開包體驗',draws:'{count} 次抽取',close:'關閉開包動畫',preparing:'正在準備卡包…',threeError:'暫時無法載入 3D 卡包，請確認瀏覽器已開啟硬體加速。',reload:'重新載入',back:'返回',tearAria:'從左向右劃開封口，或連續按右方向鍵',left:'向左旋轉卡包',right:'向右旋轉卡包',shuffling:'洗牌中…',shuffleAgain:'再次洗牌',shuffle:'洗牌',choose:'選擇目前卡包 ↗',gesture:'滑鼠或手指從左向右劃開 · 鍵盤可連續按 →',wheel:'可左右拖動的立體卡包輪盤',play:'播放開包影片',videoError:'影片暫時無法播放，請稍後重試。',result:'查看結果',skip:'跳過動畫',resultTitle:'抽取結果',prevCard:'上一張卡牌',nextCard:'下一張卡牌',recycle:'回收價值',viewCard:'查看第 {number} 張卡牌',demo:'示範結果 · 不代表實際獎品',wonCards:'本次共獲得 {count} 張收藏卡牌',stored:'卡牌已收入你的收藏倉庫',againDemo:'再體驗一次',again:'繼續抽取',finish:'完成'}
  } as const
