<script setup lang="ts">
import{computed,ref}from'vue'
import{useI18n}from'vue-i18n'
import AccountShell from'../components/AccountShell.vue'
import{cards}from'../data'
import{useAppStore}from'../stores/app'
const store=useAppStore(),mode=ref<'normal'|'recycle'|'shipping'>('normal'),selected=ref<number[]>([])
const{t}=useI18n()
const cardKeys=['pikachu','gengar','mewtwo','eevee']
const total=computed(()=>selected.value.reduce((sum,index)=>sum+cards[index].coin,0))
const modeHint=computed(()=>t(mode.value==='normal'?'accountHome.normalHint':mode.value==='recycle'?'accountHome.recycleHint':'accountHome.shippingHint'))
function toggle(i:number){selected.value=selected.value.includes(i)?selected.value.filter(x=>x!==i):[...selected.value,i]}
function finish(){store.toast(t(mode.value==='recycle'?'accountHome.recycleWarning':'accountHome.shippingStarted'))}
</script>
<template><AccountShell>
  <div class="account-title"><div><span class="eyebrow">{{t('eyebrow.collection')}}</span><h1>{{t('accountHome.title')}}</h1><p>{{t('accountHome.subtitle')}}</p></div><button class="btn btn-outline">{{t('accountHome.export')}}</button></div>
  <div class="summary"><article class="card balance-card"><span>{{t('accountHome.balance')}}</span><strong>{{store.balance.toLocaleString()}}</strong><small>{{t('accountHome.balanceHint')}}</small><div><RouterLink to="/recharge" class="btn btn-primary">{{t('accountHome.recharge')}}</RouterLink><RouterLink to="/account/transactions" class="btn btn-outline">{{t('accountHome.transactions')}}</RouterLink></div></article><article class="card warehouse-card"><span>{{t('accountHome.stored')}}</span><strong>4</strong><small>{{t('accountHome.shippingThreshold')}}</small><button class="btn btn-dark" @click="mode='shipping'">{{t('accountHome.shipPhysical')}}</button></article></div>
  <section class="warehouse card"><div class="warehouse-head"><div><h2>{{t('accountHome.warehouse')}}</h2><p>{{modeHint}}</p></div><div><button class="btn btn-outline" @click="mode='recycle';selected=[]">{{t('accountHome.batchRecycle')}}</button><button class="btn btn-dark" @click="mode='shipping';selected=[]">{{t('accountHome.shipping')}}</button></div></div>
    <div class="warehouse-tools"><div><button class="pill gold">{{t('common.all')}}</button><button class="pill">{{t('accountHome.storedStatus')}}</button><button class="pill">{{t('accountHome.shippingLocked')}}</button></div><input class="input" :placeholder="t('accountHome.search')"></div>
    <div class="card-grid"><article v-for="(card,index) in cards" :key="cardKeys[index]" class="collect-card" :class="{selected:selected.includes(index)}" @click="mode!=='normal'&&toggle(index)"><div><img :src="card.image" :alt="t(`cards.${cardKeys[index]}.name`)"><input v-if="mode!=='normal'" type="checkbox" :checked="selected.includes(index)" :disabled="index===3"></div><h3>{{t(`cards.${cardKeys[index]}.name`)}}</h3><p><span class="pill">{{t(`cards.${cardKeys[index]}.tag`)}}</span><span :class="['pill',index!==3?'green':'']">{{t(index===3?'accountHome.shippingLocked':'accountHome.storedStatus')}}</span></p><b>{{t('accountHome.recyclable',{coin:card.coin})}}</b></article><button class="add-card"><span>＋</span>{{t('accountHome.openBox')}}</button></div>
  </section>
  <div v-if="mode!=='normal'" class="selection-bar"><div><b>{{t('accountHome.selected',{count:selected.length})}}</b><span>{{t(mode==='recycle'?'accountHome.estimate':'accountHome.cardTotal',{coin:total})}}</span></div><button class="btn btn-outline" @click="mode='normal';selected=[]">{{t('common.cancel')}}</button><button class="btn btn-primary" :disabled="!selected.length||(mode==='shipping'&&total<2000)" @click="finish">{{t(mode==='recycle'?'accountHome.confirmRecycle':'common.next')}}</button></div>
</AccountShell></template>
<style scoped>.account-title{display:flex;justify-content:space-between;align-items:end;margin-bottom:20px}.account-title h1{margin:4px 0}.account-title p{margin:0;color:var(--muted)}.summary{display:grid;grid-template-columns:2fr 1fr;gap:18px}.summary article{padding:25px}.summary span,.summary small{display:block;color:var(--muted)}.summary strong{display:block;font-size:38px;color:var(--brown);margin:8px 0}.summary small{font-size:11px}.summary article>div{display:flex;gap:10px;margin-top:20px}.warehouse-card{background:var(--brown);color:#fff}.warehouse-card strong,.warehouse-card span,.warehouse-card small{color:inherit}.warehouse-card .btn{margin-top:20px;width:100%;background:white;color:var(--brown)}.warehouse{margin-top:18px;padding:24px}.warehouse-head,.warehouse-tools{display:flex;justify-content:space-between;align-items:center}.warehouse-head h2{margin:0}.warehouse-head p{font-size:12px;color:var(--muted)}.warehouse-head>div:last-child{display:flex;gap:8px}.warehouse-tools{border-top:1px solid var(--line);margin-top:18px;padding-top:18px}.warehouse-tools>div{display:flex;gap:7px}.warehouse-tools .input{width:250px}.card-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:20px}.collect-card{border:2px solid transparent;border-radius:12px;background:#fafaf7;padding:10px}.collect-card.selected{border-color:var(--gold);background:#fffbea}.collect-card>div{aspect-ratio:3/4;position:relative;border-radius:8px;overflow:hidden;background:radial-gradient(circle,#fff 0 18%,transparent 55%),linear-gradient(145deg,#fff4a5,#c4e2ff)}.collect-card img{width:100%;height:100%;padding:16px;object-fit:contain;filter:drop-shadow(0 10px 10px rgba(51,40,8,.16))}.collect-card input{position:absolute;right:8px;top:8px;width:20px;height:20px;accent-color:var(--gold)}.collect-card h3{font-size:13px}.collect-card p{display:flex;gap:4px}.collect-card b{font-size:11px;color:var(--brown)}.add-card{border:1px dashed #c9c7bb;border-radius:12px;background:white;display:grid;place-items:center;align-content:center;gap:10px}.add-card span{font-size:34px;color:var(--brown)}.selection-bar{position:fixed;z-index:45;bottom:18px;left:50%;transform:translateX(-50%);width:min(760px,calc(100% - 30px));background:#292819;color:#fff;border-radius:15px;padding:12px 16px;display:flex;align-items:center;gap:12px;box-shadow:0 20px 50px rgba(0,0,0,.25)}.selection-bar>div{margin-right:auto;display:grid}.selection-bar span{font-size:11px;color:#ddd}@media(max-width:900px){.card-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.account-title{display:block}.account-title>.btn{margin-top:15px}.summary{grid-template-columns:1fr}.warehouse{padding:16px}.warehouse-head,.warehouse-tools{align-items:stretch;display:grid;gap:12px}.warehouse-head>div:last-child{display:grid;grid-template-columns:1fr 1fr}.warehouse-tools .input{width:100%}.selection-bar{bottom:8px}.selection-bar .btn{padding:8px;font-size:12px}}</style>
