<script setup lang="ts">
import{computed,ref}from'vue'
import{useI18n}from'vue-i18n'
import{useRoute}from'vue-router'
import AccountShell from'../components/AccountShell.vue'
import{useAppStore}from'../stores/app'
const route=useRoute(),store=useAppStore(),sent=ref(false),openFaq=ref(0),{t,tm}=useI18n()
const key=computed(()=>String(route.params.page||route.path.slice(1)))
const faqs=computed(()=>tm('simple.faqQuestions') as string[])
const categories=computed(()=>tm('simple.faqCategories') as string[])
const contactCategories=computed(()=>tm('simple.categories') as string[])
const transactionHeaders=computed(()=>tm('simple.transactionHeaders') as string[])
const transactions=[{time:'08-08 14:32',type:'purchase',summary:'starlight',change:'−500',balance:'11,950'},{time:'08-08 10:04',type:'recharge',summary:'first',change:'+1,200',balance:'12,450'},{time:'08-07 18:50',type:'recycle',summary:'gengar',change:'+800',balance:'11,250'},{time:'08-01 09:20',type:'bonus',summary:'activation',change:'+100',balance:'100'}]
const isAccount=computed(()=>key.value.startsWith('account/'))
const authKey=computed(()=>key.value==='register'?'register':key.value==='forgot-password'?'forgot':key.value==='reset-password'?'reset':key.value==='account-activation'?'activation':'login')
</script>
<template>
  <AccountShell v-if="isAccount">
    <section v-if="key==='account/payment-methods'" class="simple"><span class="eyebrow">{{t('eyebrow.paymentMethods')}}</span><h1>{{t('simple.paymentTitle')}}</h1><p class="muted">{{t('simple.paymentHint')}}</p><div class="payment-grid"><article class="credit"><span>VISA</span><b>••••　••••　••••　4242</b><small>{{t('simple.expiry',{date:'08/29'})}} · {{t('simple.defaultCard')}}</small></article><article class="credit light"><span>Mastercard</span><b>••••　••••　••••　8820</b><small>{{t('simple.expiry',{date:'11/28'})}}</small></article><button class="add-payment">＋<br>{{t('simple.addCard')}}</button></div></section>
    <section v-else class="simple"><span class="eyebrow">{{t('eyebrow.transactions')}}</span><h1>{{t('simple.transactions')}}</h1><p class="muted">{{t('simple.transactionsHint')}}</p><div class="table-wrap"><table class="table"><thead><tr><th v-for="header in transactionHeaders" :key="header">{{header}}</th></tr></thead><tbody><tr v-for="row in transactions" :key="row.time"><td :data-label="transactionHeaders[0]">{{row.time}}</td><td :data-label="transactionHeaders[1]">{{t(`transactionsData.types.${row.type}`)}}</td><td :data-label="transactionHeaders[2]">{{t(`transactionsData.summaries.${row.summary}`)}}</td><td :data-label="transactionHeaders[3]" :class="{positive:row.change.startsWith('+')}">{{row.change}}</td><td :data-label="transactionHeaders[4]">{{row.balance}}</td></tr></tbody></table></div></section>
  </AccountShell>
  <main v-else class="page">
    <section v-if="key==='faq'" class="container simple"><div class="center"><span class="eyebrow">{{t('eyebrow.help')}}</span><h1>{{t('simple.faqTitle')}}</h1><p class="muted">{{t('simple.faqHint')}}</p><input class="input search" :placeholder="t('simple.faqSearch')"></div><div class="faq-layout"><aside class="card"><button v-for="(category,index) in categories" :key="category" :class="{active:index===0}">{{category}}</button></aside><div class="faq-list"><button v-for="(question,index) in faqs" :key="question" @click="openFaq=openFaq===index?-1:index"><b>{{question}}</b><span>{{openFaq===index?'−':'+'}}</span><p v-if="openFaq===index">{{t('simple.faqAnswer')}}</p></button></div></div></section>
    <section v-else-if="key==='contact'" class="container simple contact"><div><span class="eyebrow">{{t('eyebrow.contact')}}</span><h1>{{t('simple.contactTitle')}}</h1><p>{{t('simple.contactHint')}}</p><div class="support-card"><b>{{t('simple.prepare')}}</b><p>{{t('simple.prepareHint')}}</p></div></div><form class="card" @submit.prevent="sent=true"><template v-if="!sent"><div class="two"><div class="field"><label>{{t('simple.category')}}</label><select><option v-for="category in contactCategories" :key="category">{{category}}</option></select></div><div class="field"><label>{{t('simple.name')}}</label><input required></div></div><div class="field"><label>{{t('simple.email')}}</label><input type="email" required></div><div class="field"><label>{{t('simple.orderOptional')}}</label><input></div><div class="field"><label>{{t('simple.description')}}</label><textarea rows="6" required></textarea></div><div class="field"><label>{{t('simple.attachment')}}</label><input type="file" multiple></div><button class="btn btn-primary">{{t('simple.submit')}}</button></template><div v-else class="empty"><h2>{{t('simple.submitted')}}</h2><p>{{t('simple.ticket')}}<br>{{t('simple.emailSent')}}</p></div></form></section>
    <section v-else class="auth-wrap"><form class="card auth" @submit.prevent="store.toast(t('simple.submittedDemo'))"><span class="eyebrow">{{t('eyebrow.welcome')}}</span><h1>{{t(`simple.authTitles.${authKey}`)}}</h1><p class="muted">{{t(authKey==='register'?'simple.registerHint':'simple.loginHint')}}</p><div class="tabs" v-if="key==='login'"><button type="button" class="active">{{t('simple.passwordLogin')}}</button><button type="button">{{t('simple.codeLogin')}}</button></div><div class="field"><label>{{t('simple.account')}}</label><input required placeholder="name@example.com / +86"></div><div class="field" v-if="!['forgot-password','account-activation'].includes(key)"><label>{{t('simple.password')}}</label><input type="password" required></div><template v-if="key==='register'||key==='account-activation'"><div class="field"><label>{{t('simple.birth')}}</label><input type="date" required></div><label class="consent"><input type="checkbox" required> {{t('simple.consent')}}</label></template><button class="btn btn-primary">{{t('simple.continue')}}</button><RouterLink v-if="key==='login'" to="/forgot-password">{{t('simple.forgotLink')}}</RouterLink><RouterLink v-if="key==='login'" to="/register">{{t('simple.registerLink')}}</RouterLink></form></section>
  </main>
</template>
<style scoped>.simple h1{font-size:36px;margin:7px 0}.center{text-align:center}.search{max-width:560px;margin:24px auto}.faq-layout{display:grid;grid-template-columns:220px 1fr;gap:25px;margin-top:35px}.faq-layout aside{padding:12px;align-self:start}.faq-layout aside button{display:block;width:100%;border:0;background:transparent;padding:12px;text-align:left;border-radius:8px}.faq-layout aside .active{background:var(--gold);font-weight:700}.faq-list{border-top:1px solid var(--line)}.faq-list button{width:100%;text-align:left;background:white;border:0;border-bottom:1px solid var(--line);padding:20px}.faq-list span{float:right}.faq-list p{overflow:hidden;color:var(--muted);font-weight:400;line-height:1.7;transform-origin:top;animation:faq-answer-in .32s cubic-bezier(.22,.8,.3,1)}@keyframes faq-answer-in{from{max-height:0;margin-top:0;opacity:0;transform:translateY(-7px)}to{max-height:120px;opacity:1;transform:translateY(0)}}.contact{display:grid;grid-template-columns:1fr 1.2fr;gap:60px}.contact>div>p{color:var(--muted);line-height:1.8}.support-card{background:#fff9db;padding:20px;border-radius:13px;margin-top:30px}.contact form{padding:28px;display:grid;gap:16px}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.auth-wrap{min-height:70vh;display:grid;place-items:center;background:linear-gradient(135deg,#f8f7ee,#fff9cf)}.auth{width:min(460px,calc(100% - 28px));padding:35px;display:grid;gap:17px}.auth h1{margin:0}.tabs{display:grid;grid-template-columns:1fr 1fr;background:#f2f2ed;padding:4px;border-radius:10px}.tabs button{border:0;background:transparent;padding:9px}.tabs .active{background:white;border-radius:8px;box-shadow:0 2px 7px rgba(0,0,0,.06)}.consent{font-size:12px}.payment-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:30px}.credit,.add-payment{min-height:180px;border-radius:17px;padding:25px;border:0;background:linear-gradient(135deg,#272619,#705d00);color:white;display:flex;flex-direction:column;justify-content:space-between;text-align:left}.credit b{font-size:18px}.credit.light{background:linear-gradient(135deg,#ecebe3,#aaa99d);color:#333}.add-payment{background:#fff;border:1px dashed #aaa;color:var(--brown);align-items:center;justify-content:center;text-align:center;font-size:20px}.positive{color:var(--green);font-weight:700}@media(max-width:767px){.faq-layout,.contact{grid-template-columns:1fr}.faq-layout aside{display:flex;overflow:auto}.faq-layout aside button{white-space:nowrap}.payment-grid{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}}@media(max-width:450px){.payment-grid{grid-template-columns:1fr}}</style>
